name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd bank/frontend
          npm install --legacy-peer-deps

      - name: Run tests
        run: |
          cd bank/frontend
          npm test

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Din publika DNS
          username: ${{ secrets.EC2_USERNAME }}  # Användarnamn från GitHub Secrets (ubuntu)
          key: ${{ secrets.AWS_KEY }}  # Din privata SSH-nyckel från GitHub Secrets
          port: 22
          source: "bank/frontend/*"  # Filvägen för filerna att kopiera
          target: "/home/ubuntu/bank"  # Målväg på EC2

      - name: Run build and deploy commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Din publika DNS
          username: ${{ secrets.EC2_USERNAME }}  # Användarnamn från GitHub Secrets (ubuntu)
          key: ${{ secrets.AWS_KEY }}  # Din privata SSH-nyckel från GitHub Secrets
          port: 22
          script: |
            cd /home/ubuntu/bank
            npm install
            npm run build
            pm2 restart all  # Eller vad som är nödvändigt för att starta din app



