name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd bank/frontend
          npm install --legacy-peer-deps

      - name: Run tests
        run: |
          cd bank/frontend
          npm test

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_KEY }}  

      - name: Deploy to AWS
        run: |
          # Use SCP to copy files to EC2
          scp -r bank/frontend/* ubuntu@ec2-51-20-85-218.eu-north-1.compute.amazonaws.com:/home/ubuntu/bank

          # Connect via SSH and run commands on EC2
          ssh ubuntu@ec2-51-20-85-218.eu-north-1.compute.amazonaws.com << 'EOF'
            cd /home/ubuntu/bank
            npm install
            npm run build
            pm2 restart all # or any other command to restart your application
          EOF

